<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="shelf">

  <!-- ==================== -->
  <!-- Parameter Definitions -->
  <!-- ==================== -->

  <xacro:property name="shef_top_size"     value="0.5"/>
  <xacro:property name="poll_size"     value="0.01"/>
  <xacro:property name="poll_height"     value="0.5"/>


  <!-- ==================== -->
  <!-- Material Definitions -->
  <!-- ==================== -->
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>

  <!-- ==================== -->
  <!-- Link Definitions -->
  <!-- ==================== -->
  <link name="poll1">
    <visual>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09" iyy="1.1192413e-05" iyz="-1.4400107e-11" izz="2.0712558e-05" />
    </inertial>
  </link>




  <link name="poll2">
    <visual>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09" iyy="1.1192413e-05" iyz="-1.4400107e-11" izz="2.0712558e-05" />
    </inertial>
  </link>

  <joint name="poll1_joint" type="fixed">
    <parent link="poll1"/>
    <child link="poll2"/>
    <origin xyz="0.5 0.0 0.0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="poll3">
    <visual>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09" iyy="1.1192413e-05" iyz="-1.4400107e-11" izz="2.0712558e-05" />
    </inertial>
  </link>

  <joint name="poll2_joint" type="fixed">
    <parent link="poll2"/>
    <child link="poll3"/>
    <origin xyz="0.0 0.5 0.0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="poll4">
    <visual>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${poll_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${poll_size} ${poll_size} ${poll_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09" iyy="1.1192413e-05" iyz="-1.4400107e-11" izz="2.0712558e-05" />
    </inertial>
  </link>

  <joint name="poll3_joint" type="fixed">
    <parent link="poll3"/>
    <child link="poll4"/>
    <origin xyz="-0.5 0.0 0.0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="shle_top">
    <visual>
      <origin xyz="0 0 ${shef_top_size/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${shef_top_size} ${shef_top_size} 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${shef_top_size/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${shef_top_size} ${shef_top_size} 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <joint name="shlef_top_joint" type="fixed">
    <parent link="poll4"/>
    <child link="shle_top"/>
    <origin xyz="${shef_top_size/2} ${-shef_top_size/2} ${poll_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  


</robot>
